version: '3'
services:
  gitpod-backend-app:
    image: gitpod-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    networks:
      - gitpod-network
networks:
  gitpod-network:
    driver: bridge